name : Build and Deploy Next.js App 

on :
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  
jobs :
  build : 
    name : Build Next.js 
    runs-on : ubuntu-latest
    steps :
      - name : Checkout Repository 
        uses : actions/checkout@v3

      - name : Install depencencies
        run : npm install
  
      - name : Build Next.js project 
        run : npm run build

      - name : setup  Docker Buildx 
        uses : docker/setup-buildx-action@v3

      - name : Build Docker Image 
        run : docker build -t portfolio .
      
      - name : Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name : Lowercase Repository Owner
        run : echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name : Push Docker Image to GitHub Container Registry
        run : docker tag portfolio ghcr.io/${{ github.repository_owner }}/portfolio:latest
      - run : docker push ghcr.io/${{ github.repository_owner }}/portfolio:latest
    